version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"
    groups:
      internal-workflows:
        patterns:
          - "the-i-engineers/*"
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "the-i-engineers/*"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
